### ISSUE TITLE
Is there a when expression detecting whether the cursor is at the beginning of a cell?

### ISSUE THREAD

**Issue by yuriever** [microsoft/vscode-jupyter-keymap#20]
Thanks for the nice extension!

I want to custom the `notebook.cell.quitEdit` with keybinding `left arrow` when the cursor is at the beginning of a cell. Is there a when expression for this purpose or is it possible to add this functionality?

**Comment by cipri-tom** [comment]
This is a good idea ! 
Also for keybinind `up arrow`, so you don't go through the lines, but rather through cells. Wish they provide a context

**Comment by seeM** [comment]
I would like this too. I don't see any existing expression that would work. I suspect it would have to be a feature request on the main repo however: https://github.com/microsoft/vscode.
